import 'package:zcash_dart/zcash.dart';

import 'utils.dart';

void main() async {
  /// ⚠️ IMPORTANT:
  /// Before running this example, go to the `zk` folder and compile
  /// the native / wasm libraries for your target platform.
  ///
  /// Supported platforms:
  /// - Web (WASM + JS glue, optional Worker)
  /// - Android (native shared library)
  /// - Linux (native shared library)
  ///
  /// For Web:
  /// - `webWasmUrl`  → compiled `.wasm` file
  /// - `webGlueJsUrl` → JS bindings generated by wasm-pack
  /// - `workerModuleUrl` → optional web worker module for proof generation
  ///
  /// Example worker module can be found in the `zk` folder.

  final zklib = await ZKLib.init(
    ZKLibConfig(
      /// Web (WASM)
      webWasmUrl: "...",
      webGlueJsUrl: "...",

      /// Optional: Web Worker for off-main-thread proof generation
      workerModuleUrl: "...",

      /// Native platforms
      androidLibraryUrl: "...",
      linuxLibraryUrl: "...",

      /// Sapling parameter files (downloaded or bundled)
      saplingOutputParamsUrl: "...",

      /// If true, proof generation runs in a Dart isolate
      /// (recommended for non-blocking UI)
      useIsolate: false,

      /// Custom downloader for Sapling parameters
      saplingParamsDownloader: SaplingParamDownloer(),
    ),
  );

  /// Load Sapling output parameters
  /// Must be called before creating Sapling output proofs
  await zklib.setOutputParams();

  /// Load Sapling output parameters
  /// Must be called before creating Sapling speend proofs
  await zklib.setSpendParams();

  /// Create Sapling spend proofs
  await zklib.createSpendProofs([]);

  /// Create Sapling output proofs
  await zklib.createOutputProofs([]);

  /// Create Orchard proofs
  await zklib.createOrchardProof([]);

  /// ...
}
